/********************************************************************************
** Form generated from reading UI file 'formatDialog.ui'
**
** Created: Mon 16. Jan 19:04:11 2017
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FORMATDIALOG_H
#define UI_FORMATDIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_formatDialog
{
public:
    QDialogButtonBox *buttonBox;
    QGroupBox *groupBox_2;
    QCheckBox *cb1;
    QLabel *label_2;
    QLabel *label_3;
    QComboBox *type1;
    QSpinBox *start1;
    QLabel *label_4;
    QSpinBox *size1;
    QLabel *label_5;
    QSpinBox *start2;
    QCheckBox *cb2;
    QSpinBox *size2;
    QComboBox *type2;
    QLabel *label_6;
    QLabel *label_7;
    QComboBox *type3;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QSpinBox *size3;
    QCheckBox *cb3;
    QSpinBox *start3;
    QComboBox *type4;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QSpinBox *size4;
    QCheckBox *cb4;
    QSpinBox *start4;
    QComboBox *type5;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QSpinBox *size5;
    QCheckBox *cb5;
    QSpinBox *start5;
    QComboBox *type6;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QSpinBox *size6;
    QCheckBox *cb6;
    QSpinBox *start6;
    QComboBox *type7;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QSpinBox *size7;
    QCheckBox *cb7;
    QSpinBox *start7;
    QComboBox *type8;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QSpinBox *size8;
    QCheckBox *cb8;
    QSpinBox *start8;
    QLabel *label_26;
    QSpinBox *size9;
    QCheckBox *cb9;
    QLabel *label_27;
    QCheckBox *cb11;
    QSpinBox *size10;
    QLabel *label_28;
    QComboBox *type10;
    QSpinBox *start9;
    QComboBox *type9;
    QSpinBox *size11;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QComboBox *type11;
    QLabel *label_32;
    QSpinBox *start11;
    QCheckBox *cb10;
    QLabel *label_33;
    QSpinBox *start10;
    QLabel *label_34;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit;
    QLabel *label;

    void setupUi(QDialog *formatDialog)
    {
        if (formatDialog->objectName().isEmpty())
            formatDialog->setObjectName(QString::fromUtf8("formatDialog"));
        formatDialog->resize(601, 526);
        buttonBox = new QDialogButtonBox(formatDialog);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setGeometry(QRect(10, 490, 551, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        buttonBox->setCenterButtons(true);
        groupBox_2 = new QGroupBox(formatDialog);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 90, 581, 391));
        cb1 = new QCheckBox(groupBox_2);
        cb1->setObjectName(QString::fromUtf8("cb1"));
        cb1->setGeometry(QRect(20, 30, 151, 21));
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setEnabled(false);
        label_2->setGeometry(QRect(340, 30, 51, 21));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setEnabled(false);
        label_3->setGeometry(QRect(170, 30, 51, 21));
        type1 = new QComboBox(groupBox_2);
        type1->setObjectName(QString::fromUtf8("type1"));
        type1->setEnabled(false);
        type1->setGeometry(QRect(220, 30, 101, 22));
        start1 = new QSpinBox(groupBox_2);
        start1->setObjectName(QString::fromUtf8("start1"));
        start1->setEnabled(false);
        start1->setGeometry(QRect(390, 30, 51, 22));
        start1->setMinimum(1);
        start1->setMaximum(80);
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setEnabled(false);
        label_4->setGeometry(QRect(460, 30, 51, 21));
        label_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size1 = new QSpinBox(groupBox_2);
        size1->setObjectName(QString::fromUtf8("size1"));
        size1->setEnabled(false);
        size1->setGeometry(QRect(510, 30, 51, 22));
        size1->setMinimum(1);
        size1->setMaximum(80);
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setEnabled(false);
        label_5->setGeometry(QRect(460, 60, 51, 21));
        label_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        start2 = new QSpinBox(groupBox_2);
        start2->setObjectName(QString::fromUtf8("start2"));
        start2->setEnabled(false);
        start2->setGeometry(QRect(390, 60, 51, 22));
        start2->setMinimum(1);
        start2->setMaximum(80);
        cb2 = new QCheckBox(groupBox_2);
        cb2->setObjectName(QString::fromUtf8("cb2"));
        cb2->setGeometry(QRect(20, 60, 151, 21));
        size2 = new QSpinBox(groupBox_2);
        size2->setObjectName(QString::fromUtf8("size2"));
        size2->setEnabled(false);
        size2->setGeometry(QRect(510, 60, 51, 22));
        size2->setMinimum(1);
        size2->setMaximum(80);
        type2 = new QComboBox(groupBox_2);
        type2->setObjectName(QString::fromUtf8("type2"));
        type2->setEnabled(false);
        type2->setGeometry(QRect(220, 60, 101, 22));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setEnabled(false);
        label_6->setGeometry(QRect(170, 60, 51, 21));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(false);
        label_7->setGeometry(QRect(340, 60, 51, 21));
        type3 = new QComboBox(groupBox_2);
        type3->setObjectName(QString::fromUtf8("type3"));
        type3->setEnabled(false);
        type3->setGeometry(QRect(220, 90, 101, 22));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setEnabled(false);
        label_8->setGeometry(QRect(340, 90, 51, 21));
        label_9 = new QLabel(groupBox_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setEnabled(false);
        label_9->setGeometry(QRect(170, 90, 51, 21));
        label_10 = new QLabel(groupBox_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setEnabled(false);
        label_10->setGeometry(QRect(460, 90, 51, 21));
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size3 = new QSpinBox(groupBox_2);
        size3->setObjectName(QString::fromUtf8("size3"));
        size3->setEnabled(false);
        size3->setGeometry(QRect(510, 90, 51, 22));
        size3->setMinimum(1);
        size3->setMaximum(80);
        cb3 = new QCheckBox(groupBox_2);
        cb3->setObjectName(QString::fromUtf8("cb3"));
        cb3->setGeometry(QRect(20, 90, 151, 21));
        start3 = new QSpinBox(groupBox_2);
        start3->setObjectName(QString::fromUtf8("start3"));
        start3->setEnabled(false);
        start3->setGeometry(QRect(390, 90, 51, 22));
        start3->setMinimum(1);
        start3->setMaximum(80);
        type4 = new QComboBox(groupBox_2);
        type4->setObjectName(QString::fromUtf8("type4"));
        type4->setEnabled(false);
        type4->setGeometry(QRect(220, 120, 101, 22));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setEnabled(false);
        label_11->setGeometry(QRect(340, 120, 51, 21));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setEnabled(false);
        label_12->setGeometry(QRect(170, 120, 51, 21));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(false);
        label_13->setGeometry(QRect(460, 120, 51, 21));
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size4 = new QSpinBox(groupBox_2);
        size4->setObjectName(QString::fromUtf8("size4"));
        size4->setEnabled(false);
        size4->setGeometry(QRect(510, 120, 51, 22));
        size4->setMinimum(1);
        size4->setMaximum(80);
        cb4 = new QCheckBox(groupBox_2);
        cb4->setObjectName(QString::fromUtf8("cb4"));
        cb4->setGeometry(QRect(20, 120, 151, 21));
        start4 = new QSpinBox(groupBox_2);
        start4->setObjectName(QString::fromUtf8("start4"));
        start4->setEnabled(false);
        start4->setGeometry(QRect(390, 120, 51, 22));
        start4->setMinimum(1);
        start4->setMaximum(80);
        type5 = new QComboBox(groupBox_2);
        type5->setObjectName(QString::fromUtf8("type5"));
        type5->setEnabled(false);
        type5->setGeometry(QRect(220, 150, 101, 22));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setEnabled(false);
        label_14->setGeometry(QRect(340, 150, 51, 21));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(false);
        label_15->setGeometry(QRect(170, 150, 51, 21));
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(false);
        label_16->setGeometry(QRect(460, 150, 51, 21));
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size5 = new QSpinBox(groupBox_2);
        size5->setObjectName(QString::fromUtf8("size5"));
        size5->setEnabled(false);
        size5->setGeometry(QRect(510, 150, 51, 22));
        size5->setMinimum(1);
        size5->setMaximum(80);
        cb5 = new QCheckBox(groupBox_2);
        cb5->setObjectName(QString::fromUtf8("cb5"));
        cb5->setGeometry(QRect(20, 150, 151, 21));
        start5 = new QSpinBox(groupBox_2);
        start5->setObjectName(QString::fromUtf8("start5"));
        start5->setEnabled(false);
        start5->setGeometry(QRect(390, 150, 51, 22));
        start5->setMinimum(1);
        start5->setMaximum(80);
        type6 = new QComboBox(groupBox_2);
        type6->setObjectName(QString::fromUtf8("type6"));
        type6->setEnabled(false);
        type6->setGeometry(QRect(220, 190, 101, 22));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(false);
        label_17->setGeometry(QRect(340, 190, 51, 21));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setEnabled(false);
        label_18->setGeometry(QRect(170, 190, 51, 21));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(false);
        label_19->setGeometry(QRect(460, 190, 51, 21));
        label_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size6 = new QSpinBox(groupBox_2);
        size6->setObjectName(QString::fromUtf8("size6"));
        size6->setEnabled(false);
        size6->setGeometry(QRect(510, 190, 51, 22));
        size6->setMinimum(1);
        size6->setMaximum(80);
        cb6 = new QCheckBox(groupBox_2);
        cb6->setObjectName(QString::fromUtf8("cb6"));
        cb6->setGeometry(QRect(20, 190, 151, 21));
        start6 = new QSpinBox(groupBox_2);
        start6->setObjectName(QString::fromUtf8("start6"));
        start6->setEnabled(false);
        start6->setGeometry(QRect(390, 190, 51, 22));
        start6->setMinimum(1);
        start6->setMaximum(80);
        type7 = new QComboBox(groupBox_2);
        type7->setObjectName(QString::fromUtf8("type7"));
        type7->setEnabled(false);
        type7->setGeometry(QRect(220, 220, 101, 22));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setEnabled(false);
        label_20->setGeometry(QRect(340, 220, 51, 21));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setEnabled(false);
        label_21->setGeometry(QRect(170, 220, 51, 21));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setEnabled(false);
        label_22->setGeometry(QRect(460, 220, 51, 21));
        label_22->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size7 = new QSpinBox(groupBox_2);
        size7->setObjectName(QString::fromUtf8("size7"));
        size7->setEnabled(false);
        size7->setGeometry(QRect(510, 220, 51, 22));
        size7->setMinimum(1);
        size7->setMaximum(80);
        cb7 = new QCheckBox(groupBox_2);
        cb7->setObjectName(QString::fromUtf8("cb7"));
        cb7->setGeometry(QRect(20, 220, 151, 21));
        start7 = new QSpinBox(groupBox_2);
        start7->setObjectName(QString::fromUtf8("start7"));
        start7->setEnabled(false);
        start7->setGeometry(QRect(390, 220, 51, 22));
        start7->setMinimum(1);
        start7->setMaximum(80);
        type8 = new QComboBox(groupBox_2);
        type8->setObjectName(QString::fromUtf8("type8"));
        type8->setEnabled(false);
        type8->setGeometry(QRect(220, 250, 101, 22));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setEnabled(false);
        label_23->setGeometry(QRect(340, 250, 51, 21));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setEnabled(false);
        label_24->setGeometry(QRect(170, 250, 51, 21));
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setEnabled(false);
        label_25->setGeometry(QRect(460, 250, 51, 21));
        label_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        size8 = new QSpinBox(groupBox_2);
        size8->setObjectName(QString::fromUtf8("size8"));
        size8->setEnabled(false);
        size8->setGeometry(QRect(510, 250, 51, 22));
        size8->setMinimum(1);
        size8->setMaximum(80);
        cb8 = new QCheckBox(groupBox_2);
        cb8->setObjectName(QString::fromUtf8("cb8"));
        cb8->setGeometry(QRect(20, 250, 151, 21));
        start8 = new QSpinBox(groupBox_2);
        start8->setObjectName(QString::fromUtf8("start8"));
        start8->setEnabled(false);
        start8->setGeometry(QRect(390, 250, 51, 22));
        start8->setMinimum(1);
        start8->setMaximum(80);
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setEnabled(false);
        label_26->setGeometry(QRect(340, 290, 51, 21));
        size9 = new QSpinBox(groupBox_2);
        size9->setObjectName(QString::fromUtf8("size9"));
        size9->setEnabled(false);
        size9->setGeometry(QRect(510, 290, 51, 22));
        size9->setMinimum(1);
        size9->setMaximum(80);
        cb9 = new QCheckBox(groupBox_2);
        cb9->setObjectName(QString::fromUtf8("cb9"));
        cb9->setGeometry(QRect(20, 290, 151, 21));
        label_27 = new QLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setEnabled(false);
        label_27->setGeometry(QRect(170, 290, 51, 21));
        cb11 = new QCheckBox(groupBox_2);
        cb11->setObjectName(QString::fromUtf8("cb11"));
        cb11->setGeometry(QRect(20, 350, 151, 21));
        size10 = new QSpinBox(groupBox_2);
        size10->setObjectName(QString::fromUtf8("size10"));
        size10->setEnabled(false);
        size10->setGeometry(QRect(510, 320, 51, 22));
        size10->setMinimum(1);
        size10->setMaximum(80);
        label_28 = new QLabel(groupBox_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setEnabled(false);
        label_28->setGeometry(QRect(460, 320, 51, 21));
        label_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        type10 = new QComboBox(groupBox_2);
        type10->setObjectName(QString::fromUtf8("type10"));
        type10->setEnabled(false);
        type10->setGeometry(QRect(220, 320, 101, 22));
        start9 = new QSpinBox(groupBox_2);
        start9->setObjectName(QString::fromUtf8("start9"));
        start9->setEnabled(false);
        start9->setGeometry(QRect(390, 290, 51, 22));
        start9->setMinimum(1);
        start9->setMaximum(80);
        type9 = new QComboBox(groupBox_2);
        type9->setObjectName(QString::fromUtf8("type9"));
        type9->setEnabled(false);
        type9->setGeometry(QRect(220, 290, 101, 22));
        size11 = new QSpinBox(groupBox_2);
        size11->setObjectName(QString::fromUtf8("size11"));
        size11->setEnabled(false);
        size11->setGeometry(QRect(510, 350, 51, 22));
        size11->setMinimum(1);
        size11->setMaximum(80);
        label_29 = new QLabel(groupBox_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setEnabled(false);
        label_29->setGeometry(QRect(170, 320, 51, 21));
        label_30 = new QLabel(groupBox_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setEnabled(false);
        label_30->setGeometry(QRect(460, 290, 51, 21));
        label_30->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_31 = new QLabel(groupBox_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setEnabled(false);
        label_31->setGeometry(QRect(170, 350, 51, 21));
        type11 = new QComboBox(groupBox_2);
        type11->setObjectName(QString::fromUtf8("type11"));
        type11->setEnabled(false);
        type11->setGeometry(QRect(220, 350, 101, 22));
        label_32 = new QLabel(groupBox_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setEnabled(false);
        label_32->setGeometry(QRect(340, 320, 51, 21));
        start11 = new QSpinBox(groupBox_2);
        start11->setObjectName(QString::fromUtf8("start11"));
        start11->setEnabled(false);
        start11->setGeometry(QRect(390, 350, 51, 22));
        start11->setMinimum(1);
        start11->setMaximum(80);
        cb10 = new QCheckBox(groupBox_2);
        cb10->setObjectName(QString::fromUtf8("cb10"));
        cb10->setGeometry(QRect(20, 320, 151, 21));
        label_33 = new QLabel(groupBox_2);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setEnabled(false);
        label_33->setGeometry(QRect(460, 350, 51, 21));
        label_33->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        start10 = new QSpinBox(groupBox_2);
        start10->setObjectName(QString::fromUtf8("start10"));
        start10->setEnabled(false);
        start10->setGeometry(QRect(390, 320, 51, 22));
        start10->setMinimum(1);
        start10->setMaximum(80);
        label_34 = new QLabel(groupBox_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setEnabled(false);
        label_34->setGeometry(QRect(340, 350, 51, 21));
        groupBox_3 = new QGroupBox(formatDialog);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 10, 581, 71));
        lineEdit = new QLineEdit(groupBox_3);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(130, 30, 431, 20));
        label = new QLabel(groupBox_3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 30, 111, 21));
#ifndef QT_NO_SHORTCUT
        label->setBuddy(lineEdit);
#endif // QT_NO_SHORTCUT

        retranslateUi(formatDialog);
        QObject::connect(buttonBox, SIGNAL(rejected()), formatDialog, SLOT(reject()));
        QObject::connect(buttonBox, SIGNAL(accepted()), formatDialog, SLOT(accept()));
        QObject::connect(cb1, SIGNAL(toggled(bool)), label_3, SLOT(setEnabled(bool)));
        QObject::connect(cb1, SIGNAL(toggled(bool)), type1, SLOT(setEnabled(bool)));
        QObject::connect(cb1, SIGNAL(toggled(bool)), label_2, SLOT(setEnabled(bool)));
        QObject::connect(cb1, SIGNAL(toggled(bool)), start1, SLOT(setEnabled(bool)));
        QObject::connect(cb1, SIGNAL(toggled(bool)), label_4, SLOT(setEnabled(bool)));
        QObject::connect(cb1, SIGNAL(toggled(bool)), size1, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), label_6, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), type3, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), type2, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), label_7, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), start2, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), label_5, SLOT(setEnabled(bool)));
        QObject::connect(cb2, SIGNAL(toggled(bool)), size2, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), label_9, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), label_8, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), start3, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), label_10, SLOT(setEnabled(bool)));
        QObject::connect(cb3, SIGNAL(toggled(bool)), size3, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), label_12, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), type4, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), label_11, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), start4, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), label_13, SLOT(setEnabled(bool)));
        QObject::connect(cb4, SIGNAL(toggled(bool)), size4, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), label_15, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), type5, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), label_14, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), start5, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), label_16, SLOT(setEnabled(bool)));
        QObject::connect(cb5, SIGNAL(toggled(bool)), size5, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), label_18, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), type6, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), label_17, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), start6, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), label_19, SLOT(setEnabled(bool)));
        QObject::connect(cb6, SIGNAL(toggled(bool)), size6, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), label_21, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), type7, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), label_20, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), start7, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), label_22, SLOT(setEnabled(bool)));
        QObject::connect(cb7, SIGNAL(toggled(bool)), size7, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), label_24, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), type8, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), label_23, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), start8, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), label_25, SLOT(setEnabled(bool)));
        QObject::connect(cb8, SIGNAL(toggled(bool)), size8, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), label_27, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), type9, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), label_26, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), start9, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), label_30, SLOT(setEnabled(bool)));
        QObject::connect(cb9, SIGNAL(toggled(bool)), size9, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), type10, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), label_29, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), label_32, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), start10, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), label_28, SLOT(setEnabled(bool)));
        QObject::connect(cb10, SIGNAL(toggled(bool)), size10, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), label_31, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), type11, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), label_34, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), start11, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), label_33, SLOT(setEnabled(bool)));
        QObject::connect(cb11, SIGNAL(toggled(bool)), size11, SLOT(setEnabled(bool)));

        QMetaObject::connectSlotsByName(formatDialog);
    } // setupUi

    void retranslateUi(QDialog *formatDialog)
    {
        formatDialog->setWindowTitle(QString());
        groupBox_2->setTitle(QApplication::translate("formatDialog", "Format Definition", 0, QApplication::UnicodeUTF8));
        cb1->setText(QApplication::translate("formatDialog", "&Serial Number", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb2->setText(QApplication::translate("formatDialog", "&Atom Title", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb3->setText(QApplication::translate("formatDialog", "&Residue Number", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb4->setText(QApplication::translate("formatDialog", "R&esidue Title", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb5->setText(QApplication::translate("formatDialog", "&Chain Identifier", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb6->setText(QApplication::translate("formatDialog", "&Position X", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb7->setText(QApplication::translate("formatDialog", "&Position Y", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        cb8->setText(QApplication::translate("formatDialog", "&Position Z", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        cb9->setText(QApplication::translate("formatDialog", "&Force X", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        cb11->setText(QApplication::translate("formatDialog", "&Force Z", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("formatDialog", "Type:", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        cb10->setText(QApplication::translate("formatDialog", "&Force Y", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("formatDialog", "Size:", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("formatDialog", "Start:", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("formatDialog", "Format Settings", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("formatDialog", "Format &Title:", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class formatDialog: public Ui_formatDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FORMATDIALOG_H
